spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meuflix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true





