spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username:
    password:
  jpa:

    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show_sql: true
      format_sql: true



